gitSourceBranch = "master"
changelog = false
classOrder = []
apiCategories = [
    "events"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

url = "https://www.brittonfischer.com"

[footer]
style = "dark"
copyright = "Copyright © 2021 Britton Fischer. Built with Moonwave and Docusaurus"