[package]
name = "brittonfischer/geometrydash"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.6"
Janitor = "howmanysmall/janitor@1.14.1"
Promise = "evaera/promise@4.0.0"
Symbol = "sleitnick/symbol@2.0.1"
Signal = "sleitnick/signal@1.0.1"
Spring = "brittonfischer/spring@0.1.0"
CameraShaker = "brittonfischer/camerashaker@0.1.0"
ReplicaService = "brittonfischer/replicaservice@0.1.0"
Fusion = "elttob/fusion@0.2.0"
FusionExtensions = "nottirb/fusionextensions@0.2.0-rc1"
StoryTaskBar = "nottirb/storytaskbar@0.2.0-rc1"

[server-dependencies]
ProfileService = "brittonfischer/profileservice@2.1.5"